[package]
name = "glutin_title"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = "0.11"
prototty_glutin = "0.11"
prototty_title = { path = "../prototty" }
