[package]
name = "prototty_decorators"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_traits = { path = "../traits" }
prototty_defaults = { path = "../defaults" }
serde = "1.0"
serde_derive = "1.0"
