[package]
name = "prototty"
description = "Library for rapid prototyping of terminal UIs"
version = "0.2.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
libc = "0.2"
term = "0.4"
cgmath = "0.15"
terminal_colour = "0.2"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "echo_timeout"
path = "examples/echo_timeout.rs"

[[example]]
name = "echo_poll"
path = "examples/echo_poll.rs"

[[example]]
name = "echo_wait"
path = "examples/echo_wait.rs"

[[example]]
name = "basic_context"
path = "examples/basic_context.rs"

[[example]]
name = "context_bench"
path = "examples/context_bench.rs"
