[package]
name = "prototty"
description = "Definition of traits for terminal rendering"
version = "0.5.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[dependencies]
prototty_traits = { path = "./traits" }
prototty_menu = { path = "./menu" }
prototty_decorators = { path = "./decorators" }
prototty_text = { path = "./text" }
prototty_input = { path = "./input" }
prototty_elements = { path = "./elements" }
prototty_unix = { path = "./unix" }
prototty_wasm = { path = "./wasm" }

[[example]]
name = "bordered_menu"
path = "examples/bordered_menu.rs"
