[package]
name = "prototty_elements"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_traits = { path = "../traits" }
prototty_text = { path = "../text" }
serde = "1.0"
serde_derive = "1.0"
