[package]
name = "prototty_grid"
description = "Implementation of prototty::ViewGrid for use in renderers."
version = "0.11.2"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_grid"

[dependencies]
prototty = { path = "../prototty", version = "0.11.2" }
itertools = "0.7"
