[package]
name = "prototty_grid"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_defaults = { path = "../defaults" }
prototty_traits = { path = "../traits" }
