[package]
name = "prototty_wasm"
description = "Prototty context for web assembly."
version = "0.6.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"

[dependencies]
prototty = { path = "..", version = "0.6.0" }
itertools = "0.7"
