[package]
name = "prototty_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
itertools = "0.7"
prototty = { path = ".." }
prototty_grid = { path = "../grid" }
