[package]
name = "prototty_wasm"
description = "Prototty context for web assembly."
version = "0.12.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"

[dependencies]
prototty = { path = "../prototty", version = "0.12.0" }
prototty_grid = { path = "../grid", version = "0.12.0" }
itertools = "0.7"
