[package]
name = "prototty_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_traits = { path = "../traits" }
prototty_grid = { path = "../grid" }
itertools = "0.7"
