[package]
name = "unix_title_border"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = "0.11"
prototty_unix = "0.11"
prototty_common = "0.11"
prototty_title = { path = "../prototty" }
