[package]
name = "prototty_memory_storage"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = { path = "../prototty", version = "0.13.0" }
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9.2"
