[package]
name = "prototty_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
libc = "0.2"
term = "0.4"
ansi_colour = "0.2"
itertools = "0.7"
prototty = { path = ".." }
prototty_grid = { path = "../grid" }
prototty_defaults = { path = "../defaults" }

[[example]]
name = "bordered_menu"
path = "examples/bordered_menu.rs"
