[package]
name = "prototty_unix"
description = "Prototty context for unix terminals."
version = "0.6.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_unix"

[dependencies]
prototty = { path = "..", version = "0.6.0" }
libc = "0.2"
term = "0.4"
ansi_colour = "0.2"
itertools = "0.7"
