[package]
name = "prototty_unix"
description = "Prototty context for unix terminals."
version = "0.11.2"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_unix"

[dependencies]
prototty = { path = "../prototty", version = "0.11.2" }
prototty_grid = { path = "../grid", version = "0.11.2" }
libc = "0.2"
term = "0.4"
ansi_colour = "0.4"
itertools = "0.7"
