[package]
name = "prototty_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
libc = "0.2"
term = "0.4"
cgmath = "0.15"
ansi_colour = "0.2"
itertools = "0.7"
prototty_defaults = { path = "../defaults" }
prototty_input = { path = "../input" }
prototty_traits = { path = "../traits" }
prototty_grid = { path = "../grid" }
