[package]
name = "prototty_traits"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
cgmath = { git = "https://github.com/stevebob/cgmath", rev = "rand-0.4", features = ["serde"] }
ansi_colour = "0.2"
