[package]
name = "prototty_glutin"
description = "Prototty context for glutin windows."
version = "0.8.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_glutin"

[dependencies]
prototty = { path = "..", version = "0.8.0" }
prototty_grid = { path = "../grid", version = "0.8.0" }
glutin = "0.9"
gfx_window_glutin = "0.17"
gfx_device_gl = "0.14"
gfx = "0.16"
gfx_glyph = "0.6"
itertools = "0.7"
