[package]
name = "prototty_menu"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_coord = { path = "../coord" }
prototty_traits = { path = "../traits" }
prototty_defaults = { path = "../defaults" }
prototty_text = { path = "../text" }
prototty_input = { path = "../input" }
serde = "1.0"
serde_derive = "1.0"
ansi_colour = "0.2"
