[package]
name = "prototty_menu"
description = "Interactive menu which can be rendered with prototty and handle prototty input events."
version = "0.8.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_menu"

[dependencies]
prototty_coord = { path = "../coord", version = "0.8.0" }
prototty_traits = { path = "../traits", version = "0.8.0" }
prototty_defaults = { path = "../defaults", version = "0.8.0" }
prototty_text = { path = "../text", version = "0.8.0" }
prototty_input = { path = "../input", version = "0.8.0" }
serde = "1.0"
serde_derive = "1.0"
ansi_colour = "0.2"
