[package]
name = "prototty_text"
description = "Text utilities for use with prototty."
version = "0.8.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_text"

[dependencies]
prototty_defaults = { path = "../defaults", version = "0.8.0" }
ansi_colour = "0.2"
serde = "1.0"
serde_derive = "1.0"
